# Directories to backup: paths without spaces in their name
BACKUP_MANAGER_TARBALL_DIRECTORIES: "/data-to-backup /data-to-backup2"

# Run backup-manager at 4:00am
BACKUP_MANAGER_CRON_EXP: "0 4 * * *"

# Delete backups that are over 15 days
BACKUP_MANAGER_TTL: 15

# Ftp upload config
BACKUP_MANAGER_UPLOAD_METHOD: ftp
BACKUP_MANAGER_UPLOAD_HOSTS: ftp.example.org
BACKUP_MANAGER_UPLOAD_FTP_USER: ftp-user
BACKUP_MANAGER_UPLOAD_FTP_PASSWORD: ftp-password
BACKUP_MANAGER_UPLOAD_DESTINATION: /
BACKUP_MANAGER_UPLOAD_TTL: 60 # Delete backups on the ftp that are over 60 days
BACKUP_PRE_BACKUP_COMMAND: /container/cmd/pre.sh
BACKUP_POST_BACKUP_COMMAND: /container/cmd/post.sh

# Encryption, disabled if empty
BACKUP_MANAGER_ENCRYPTION: false
BACKUP_MANAGER_ENCRYPTION_RECIPIENT: Mike Ross
